### ISSUE TITLE
Animated assembley of Sense HAT

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/addons-guide#2]
@samalderhyde would it be possible to get a gif of then Sense HAT being lowered onto a Raspberry Pi with the spacers and machine screws securing it in place?

**Comment by samalderhyde** [comment]
SHould be fine. I'll take a look when I get a chance and let you know an ETA on it

**Comment by lawsie** [comment]
Does this exist? Should it exist? Should I waffle this for Sam or close the issue?

**Comment by MarcScott** [comment]
Yeah, waffle-it
